server:
  port: 8085
spring:
  r2dbc:
    username: postgres
    password: 2002
    url: r2dbc:postgresql://localhost:5432/library_db
springdoc:
  swagger-ui:
    path: /swagger-ui

producer:
  service:
    url: http://localhost:8081/